(integer? 3.0)
(integer? 0.0)
(integer? -0.0)
(integer? -3.0)
(integer? -3.5)
(integer? 3.5)
(integer? 3)
(integer? 0)
(integer? -3)
(integer? -0)
(integer? 5/6)
(integer? -5/6)
(integer? (/ 5 -6))
(integer? (/ -5 -6))
(integer? car)
(integer? 'car)
(integer? (lambda (x) x))
(integer? '(lambda (x) x))
(integer? '()) 
(integer? '(a))
(integer? #\x)
(integer? #f)
(integer? '(a b c))
(integer? "hi")
(integer? 'hi)
(integer? #\h)
(integer? 't) 
(integer? "t")
(integer? '(t))
(integer? #\t)
(integer? #t)