(number? 3)
(number? 3.0)
(number? 3.5)
(number? 0)
(number? 0.0)
(number? -3)
(number? -3.0)
(number? -3.5)
(number? -0)
(number? -0.0)
(number? 5/6)
(number? -5/6)
(number? (/ 5 -6))
(number? (/ -5 -6))
(number? car)
(number? 'car)
(number? (lambda (x) x))
(number? '(lambda (x) x))
(number? '()) 
(number? '(a))
(number? #\x)
(number? #f)
(number? '(a b c))
(number? "hi")
(number? 'hi)
(number? #\h)
(number? 't) 
(number? "t")
(number? '(t))
(number? #\t)
(number? #t)